### ISSUE TITLE
HTTP connector in `camunda/connectors:0.2.0-rc1-ootb` image fails to evaluate response mapping expression

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/connector-sdk#135]
__Describe the Bug__

I'm trying to run the ootb connectors via `camunda/connectors:0.2.0-rc1-ootb`.

Using the rest connector with a result mapping fails:

```
Sep 29, 2022 10:51:16 AM io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler handle
INFO: Received job 2251799813851702
Sep 29, 2022 10:51:16 AM io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler handle
SEVERE: Failed to process job 2251799813851702
io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapperException: Failed to evaluate expression '=result.body.id' and context 'HttpJsonResult{status=200, headers={date=Thu, 29 Sep 2022 10:51:16 GMT, transfer-encoding=chunked, keep-alive=timeout=60, content-type=application/vnd.spring-boot.actuator.v3+json, connection=keep-alive}, body={id=310}}', because expression evaluation failed
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:84)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.lambda$createOutputVariables$0(ConnectorJobHandler.java:97)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.createOutputVariables(ConnectorJobHandler.java:97)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:73)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class io.camunda.connector.http.model.HttpJsonResult cannot be cast to class java.util.Map (io.camunda.connector.http.model.HttpJsonResult is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.ensureVariablesMap(FeelEngineWrapper.java:70)
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:75)
	... 12 more
```

The expression I used is `= result.body.id`. In the exception we can see that this variable is available.

__Steps to Reproduce__

1. Deploy `camunda/connectors:0.2.0-rc1-ootb`
2. Use the HTTP connector with a response mapping expression

__Expected Behavior__

The HTTP connector in the OOTB docker image can evaulate response mapping expression.

**Comment by igpetrov** [comment]
Good day @oleschoenburg,

Thank you for reporting the ticket.

I think, there's something wrong with the expression itself: `Failed to evaluate expression '=result.body.id'`. (1) AFAIK, to evaluate the result expression you would need a variable that will be exposed to the context. Also, the default result context is stored in the `response` variable. See a working example:

<img width="742" alt="Screenshot 2022-10-04 at 14 16 53" src="https://user-images.githubusercontent.com/108870003/193805418-4d4d5bf5-eab8-47d3-a29c-ca1ffa620ca6.png">

<img width="951" alt="Screenshot 2022-10-04 at 14 17 41" src="https://user-images.githubusercontent.com/108870003/193805505-91d66103-24da-4004-90bf-82c183f2d015.png">

Please let us know if this resolves your issue.

Thank you.

**Comment by oleschoenburg** [comment]
@igpetrov Thanks for looking into it! :+1: 

> Also, the default result context is stored in the response variable

:facepalm: Thanks, that was my mistake. However I'm still getting the same exception after adjusting the expression. Here is a simple model to reproduce:

[simple-rest-process.zip](https://github.com/camunda/connector-sdk/files/9706932/simple-rest-process.zip)

The expression is now just `=response.body`, mapped to a new variable called `body`. AFAIK this should work?

The logs from the connectors container look like there are classloader issues:

```
io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapperException: Failed to evaluate expression '=response.body' and context 'HttpJsonResult{status=200, headers={date=Tue, 04 Oct 2022 12:37:03 GMT, transfer-encoding=chunked, keep-alive=timeout=60, content-type=application/vnd.spring-boot.actuator.v3+json, connection=keep-alive}, body={backupId=110, status=COMPLETED, failureReason=java.lang.Object@28814363, partitions=[{partitionId=1, status=COMPLETED, description={snapshotId=, checkpointPosition=29208, brokerId=1, brokerVersion=8.1.0}, failureReason=java.lang.Object@28814363, createdAt=2022-10-04T12:29:49.824635836Z, lastUpdatedAt=2022-10-04T12:29:50.562648101Z}, {partitionId=2, status=COMPLETED, description={snapshotId=, checkpointPosition=130946, brokerId=1, brokerVersion=8.1.0-SNAPSHOT}, failureReason=java.lang.Object@28814363, createdAt=2022-09-29T10:36:42.079653175Z, lastUpdatedAt=2022-09-29T10:36:44.059903006Z}, {partitionId=3, status=COMPLETED, description={snapshotId=338116-1-1026825-1025098, checkpointPosition=3020625, brokerId=2, brokerVersion=8.1.0-SNAPSHOT}, failureReason=java.lang.Object@28814363, createdAt=2022-09-29T07:19:53.715945204Z, lastUpdatedAt=2022-09-29T07:20:24.985795057Z}]}}', because expression evaluation failed
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:84)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.lambda$createOutputVariables$0(ConnectorJobHandler.java:97)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.createOutputVariables(ConnectorJobHandler.java:97)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:73)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class io.camunda.connector.http.model.HttpJsonResult cannot be cast to class java.util.Map (io.camunda.connector.http.model.HttpJsonResult is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.ensureVariablesMap(FeelEngineWrapper.java:70)
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:75)
	... 12 more
```

**Comment by nikku** [comment]
@oleschoenburg What do you want to accomplish through the following?

```
        <zeebe:taskHeaders>
          <zeebe:header key="resultVariable" value="body" />
          <zeebe:header key="resultExpression" value="=response.body" />
        </zeebe:taskHeaders>
```

As [indicated in the docs](https://docs.camunda.io/docs/next/components/integration-framework/connectors/out-of-the-box-connectors/rest/#response) the result expression shall be used to extract individual parts of the response into a `FEEL Context`:

```
= {
  body: response.body
}
```

**Comment by nikku** [comment]
Independent of this we should ensure we handle other uses like the one that you showcase gracefully.

**Comment by oleschoenburg** [comment]
Ohhhh, now I get it :facepalm: Sorry, I did not read the docs carefully enough. I though an expression like `=response.body.id` could be mapped to the variable `id` but I understand now that the expression needs to evaluate to a map. Feel free to close this issue or rename as UX instead of a bug issue.
Thanks for helping out <3

**Comment by nikku** [comment]
Keeping open. Your issue is likely some other persons issue, too.

**Comment by menski** [comment]
I can reproduce the behavior described from Ole, using the self managed distribution from https://github.com/camunda/camunda-platform/pull/35 and the following bpmn model [http-post.bpmn.txt](https://github.com/camunda/connector-sdk/files/9708051/http-post.bpmn.txt)

The model works as expected in SaaS but fails in Self-Managed with the following exception
```
SEVERE: Failed to process job 2251799813685265
io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapperException: Failed to evaluate expression '={ json: response.body.json }' and context 'HttpJsonResult{status=200, headers={date=Tue, 04 Oct 2022 14:41:06 GMT, access-control-allow-origin=*, content-length=467, server=gunicorn/19.9.0, access-control-allow-credentials=true, content-type=application/json, connection=keep-alive}, body={args={}, data={"hello":"world"}, files={}, form={}, headers={Accept-Encoding=gzip, Content-Length=17, Content-Type=application/json, Host=httpbin.org, User-Agent=Google-HTTP-Java-Client/1.42.2 (gzip), X-Amzn-Trace-Id=Root=1-633c4602-30a9825f4a7f5ec656c2f958}, json={hello=world}, origin=79.202.44.92, url=https://httpbin.org/post}}', because expression evaluation failed
        at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:84)
        at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.lambda$createOutputVariables$0(ConnectorJobHandler.java:96)
        at java.base/java.util.Optional.map(Unknown Source)
        at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.createOutputVariables(ConnectorJobHandler.java:96)
        at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:72)
        at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
        at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class io.camunda.connector.http.model.HttpJsonResult cannot be cast to class java.util.Map (io.camunda.connector.http.model.HttpJsonResult is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')
        at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.ensureVariablesMap(FeelEngineWrapper.java:70)
        at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:75)
        ... 12 more
```

It could be a class loading issue, or related with job worker implementation to handle result expressions. I will root cause the issue further.

**Comment by menski** [comment]
I was able to write a failing test case https://github.com/camunda/connector-sdk/commit/3082923dbcd73006466a44e29ac606b01b56cc25. It seems the root cause is that our connector functions in the job worker runtime are returning POJOs which then the runtime is trying to [cast to a Map](https://github.com/camunda/connector-sdk/blob/ce2cd0a27f7d014624907769112a76a4a5c4c749/runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapper.java#L68-L71), which fails.

**Comment by PreetiNirwal** [comment]
Thank you @menski @igpetrov @nikku for your work on resolving this!
