### ISSUE TITLE
HTTP connector execution fails when response JSON contains `null` values

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/connector-sdk#153]
__Describe the Bug__

Using the http-json connector to query an API that returns JSON where some fields are `null` results in an exception while evaluating an output variable expression that reads like `null` is not supported by the object mapper used to convert the connector result to JSON.

```
io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapperException: Failed to evaluate expression '={status: response.body.status}' and context 'HttpJsonResult{status=200, headers={date=Wed, 05 Oct 2022 13:08:01 GMT, transfer-encoding=chunked, keep-alive=timeout=60, content-type=application/vnd.spring-boot.actuator.v3+json, connection=keep-alive}, body={backupId=700, status=COMPLETED, failureReason=java.lang.Object@157c77c3, partitions=[{partitionId=1, status=COMPLETED, description={snapshotId=839860-2-1159347-1159109, checkpointPosition=1353282, brokerId=1, brokerVersion=8.1.0}, failureReason=java.lang.Object@157c77c3, createdAt=2022-10-04T13:43:52.901068692Z, lastUpdatedAt=2022-10-04T13:43:55.612012619Z}, {partitionId=2, status=COMPLETED, description={snapshotId=958696-1-1321649-1320638, checkpointPosition=1353064, brokerId=1, brokerVersion=8.1.0}, failureReason=java.lang.Object@157c77c3, createdAt=2022-10-04T13:43:52.900913208Z, lastUpdatedAt=2022-10-04T13:43:55.499697877Z}, {partitionId=3, status=COMPLETED, description={snapshotId=887461-1-1231853-1231786, checkpointPosition=1352981, brokerId=2, brokerVersion=8.1.0}, failureReason=java.lang.Object@157c77c3, createdAt=2022-10-04T13:43:52.907161982Z, lastUpdatedAt=2022-10-04T13:43:55.508196412Z}]}}', because expression evaluation failed
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:86)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.lambda$createOutputVariables$0(ConnectorJobHandler.java:97)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.createOutputVariables(ConnectorJobHandler.java:97)
	at io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:73)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.camunda.connector.http.model.HttpJsonResult["body"]->com.google.api.client.util.ArrayMap["failureReason"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4334)
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.ensureVariablesMap(FeelEngineWrapper.java:72)
	at io.camunda.connector.runtime.jobworker.impl.feel.FeelEngineWrapper.evaluateToJson(FeelEngineWrapper.java:77)
	... 12 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.camunda.connector.http.model.HttpJsonResult["body"]->com.google.api.client.util.ArrayMap["failureReason"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4371)
	... 15 more
```

__Steps to Reproduce__

1. Query an API that returns JSON with `null` values, for example `{"status": 200, "failure": null}`
2. Use response mapping expression such as `= {status: response.body.status}`

__Expected Behavior__

`null` is a valid JSON value and should be supported, at least in the sense that they don't crash the connector as long as they are not explicitly mapped to feel variables.

__Environment__

- Connectors: camunda/connectors-bundle:0.1.0-rc2

**Comment by menski** [comment]
Turns out this seems not to be null values, but some form of wrong serialization. As seen in Oles response the `failureReason` is some kind of Java Object `failureReason=java.lang.Object@157c77c3`, which leads to the exception as the Object Mapper is not aware of what to do with it.

As mitigation we can configure the object mapper to ignore such fields.

But to also understand the impact, my question is if this is a problem in our HTTP connector, or is this the response from the API Ole is accessing. Noteable is the content type of the response `content-type=application/vnd.spring-boot.actuator.v3+json`, I'm not familiar with the spring boot actuator details regarding response formats, but something to investigate.
